name: magic_image
description: "A Flutter package that simplifies advanced image loading, display, and interaction."
version: 0.0.1
homepage: https://github.com/gktirkha/magic_image
repository: https://github.com/gktirkha/magic_image


environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter: 
